'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');
const {validateCheckpoint,writePrivate}=require('../skill/scripts/session-budget');
const valid=()=>({goal:'Finish the task',nextAction:'Run verification',constraints:[],changedFiles:['src/a.js'],verification:['node --test passes'],blockers:[],authorization:['User requested commit and push']});
test('checkpoint retains actionable state and omits unknown fields',()=>{assert.deepEqual(validateCheckpoint({...valid(),extra:'ignored'}),valid());});
test('checkpoint refuses incomplete, oversized and credential-bearing state',()=>{assert.throws(()=>validateCheckpoint({goal:'x'}));assert.throws(()=>validateCheckpoint({...valid(),goal:'x'.repeat(33000)}),/32 KB/);assert.throws(()=>validateCheckpoint({...valid(),goal:'sk-proj-'+ 'x'.repeat(25)}),/credential/);});
test('checkpoint writes atomically with private permissions',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'route3-checkpoint-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'run/checkpoint.json');writePrivate(file,valid());writePrivate(file,{...valid(),nextAction:'Review diff'});assert.equal(JSON.parse(fs.readFileSync(file)).nextAction,'Review diff');assert.equal(fs.statSync(file).mode&0o777,0o600);assert.deepEqual(fs.readdirSync(path.dirname(file)),['checkpoint.json']);});

const {usageDeltas}=require('../skill/scripts/session-budget');
test('spend deltas require same-session cumulative baselines and detect resets',()=>{const session={id:'a',provider:'codex',measurement:{usage:'reported_cumulative'},inputTokens:100,outputTokens:20,cachedInputTokens:80,totalTokens:120};const previous={at:'before',sessions:[session]};assert.equal(usageDeltas(previous,{sessions:[{...session,inputTokens:150,totalTokens:170}]})[0].inputTokens,50);assert.equal(usageDeltas(previous,{sessions:[{...session,totalTokens:10}]})[0].status,'counter_reset');assert.equal(usageDeltas(previous,{sessions:[{...session,id:'b'}]})[0].status,'baseline_or_partial');assert.equal(usageDeltas(previous,{sessions:[{...session,measurement:{usage:'partial_messages'}}]})[0].status,'baseline_or_partial');});
